package:
  name: "ctranslate2-lib"
  version: "4.1.0"

source:
  git_url: https://github.com/OpenNMT/CTranslate2.git
  git_rev: v4.1.0  # Use the correct version tag

build:
  number: 0

requirements:
  build:
    - cmake 3.30.2
